//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graph_.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Graph_.Localization.titles", typeof(titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove all edges?.
        /// </summary>
        internal static string clearGraphRequest {
            get {
                return ResourceManager.GetString("clearGraphRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove edges?.
        /// </summary>
        internal static string clearGraphTitle {
            get {
                return ResourceManager.GetString("clearGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges:.
        /// </summary>
        internal static string edgesTitle {
            get {
                return ResourceManager.GetString("edgesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File error.
        /// </summary>
        internal static string fileErrorTitle {
            get {
                return ResourceManager.GetString("fileErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant parse graph, check the file..
        /// </summary>
        internal static string parseError {
            get {
                return ResourceManager.GetString("parseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to.
        /// </summary>
        internal static string saveFileRequest {
            get {
                return ResourceManager.GetString("saveFileRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language preferences will change after restart..
        /// </summary>
        internal static string savingChangesMessage {
            get {
                return ResourceManager.GetString("savingChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartTitle {
            get {
                return ResourceManager.GetString("StartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopTitle {
            get {
                return ResourceManager.GetString("StopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file type..
        /// </summary>
        internal static string unknownFileError {
            get {
                return ResourceManager.GetString("unknownFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices:.
        /// </summary>
        internal static string verticesTitle {
            get {
                return ResourceManager.GetString("verticesTitle", resourceCulture);
            }
        }
    }
}
